# Option-1 : Createting docker container using command module 
---
- hosts: all
  become: true

  tasks:
  - name: creating docker image using docker command
    command: docker run -d --name sample-devops-container -p 8080:8080 sample-devops-image
	
# option-2 : creating docker container using docker_container module 	
#  tasks:
#  - name: create sample-devops-container
#    docker_container:
#      name: sample-devops-container
#      image: sample-devops-image
#      state: present
#      recreate: yes
#      ports:
#        - "8080:8080"
